spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.show_sql: true
  datasource:
    url: jdbc:h2:file:~/h2/social-multiplication;DB_CLOSE_ON_EXIT=FALSE
